#spring.application.name=identity
#
## MySQL Database Configuration
#
## JDBC URL → tells Spring Boot where the MySQL database is located.
## 127.0.0.1 = localhost, 3306 = MySQL default port, identity= database name
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/identity
#
## Database username used to authenticate with MySQL
#spring.datasource.username=root
#
## Password for the database user
#spring.datasource.password=root
#
## JDBC driver class → allows Java/Spring to communicate with MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
## JPA / Hibernate Configuration
#
## ddl-auto=update → Hibernate automatically updates database tables
## to match your Entity classes (adds columns/tables without deleting data)
#spring.jpa.hibernate.ddl-auto=update
#
## show-sql=true → prints executed SQL queries in the console (useful for debugging)
#spring.jpa.show-sql=true
#
## Specifies SQL dialect so Hibernate generates MySQL-8 compatible queries
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.application.name=identity

# Uses Render env variables in production, falls back to local values in dev
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/identity}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect